"""Execution layer module."""

from .executors import (
    ExecutorBase,
    BinaryExecutor,
    MT5SpotExecutor,
    ArbitrageExecutor,
    ForexExecutor,
    RealTimeExecutionHub,
    ShadowExecutionHub,
)
from .brokers import (
    BrokerBridge,
    CCXTBrokerBridge,
    OandaBrokerBridge,
    AlpacaBrokerBridge,
    BinaryOptionsBridge,
    Web3ArbitrageBridge,
    create_broker_bridge,
)
from .arbitrage_calculator import (
    MultiHopArbitrageCalculator,
    UniversalArbitrageCalculator,
    OmniArbV2Calculator,
    Exchange,
    TradingPair,
    ArbitrageRoute,
    FlashLoanParams,
    UniversalArbitrageResult,
    RouteType,
    CalculatorType,
    # OmniArb V2 Zone 6 components
    FlashLoanSource,
    FlashLoanSourceConfig,
    ChainType,
    ChainConfig,
    TotalCostOfExecution,
    LiquidityDepth,
    TriangularArbitrageOpportunity,
    Zone6Result,
    format_arbitrage_report,
    format_comparison_report,
    format_zone6_report,
)

__all__ = [
    # Executors
    "ExecutorBase",
    "BinaryExecutor",
    "MT5SpotExecutor",
    "ArbitrageExecutor",
    "RealTimeExecutionHub",
    "ShadowExecutionHub",
    # Brokers
    "BrokerBridge",
    "CCXTBrokerBridge",
    "OandaBrokerBridge",
    "AlpacaBrokerBridge",
    "BinaryOptionsBridge",
    "Web3ArbitrageBridge",
    "create_broker_bridge",
    # Arbitrage Calculators
    "MultiHopArbitrageCalculator",
    "UniversalArbitrageCalculator",
    "OmniArbV2Calculator",
    "Exchange",
    "TradingPair",
    "ArbitrageRoute",
    "FlashLoanParams",
    "UniversalArbitrageResult",
    "RouteType",
    "CalculatorType",
    # OmniArb V2 Zone 6 components
    "FlashLoanSource",
    "FlashLoanSourceConfig",
    "ChainType",
    "ChainConfig",
    "TotalCostOfExecution",
    "LiquidityDepth",
    "TriangularArbitrageOpportunity",
    "Zone6Result",
    "format_arbitrage_report",
    "format_comparison_report",
    "format_zone6_report",
]
